// -*- C++ -*- generated by wxGlade 0.3.1 on Fri Oct 31 17:57:26 2003

#include "DlgNewObject.h"

BEGIN_EVENT_TABLE(NewObjectDialog, wxDialog)
EVT_BUTTON(wxID_OK, NewObjectDialog::OnOK)
END_EVENT_TABLE()

#include "kazam.h"
extern MainFrame *frame;

void NewObjectDialog::OnOK(wxCommandEvent& event)
{
  // Check and warn if the ID is bad
  if(!frame->project.IsUniqueID(editID->GetValue(), this)) return;
  event.Skip();
}

NewObjectDialog::NewObjectDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: NewObjectDialog::NewObjectDialog
    labelIntro = new wxStaticText(this, -1, wxT("Please enter the object ID:\n"));
    labelID = new wxStaticText(this, -1, wxT("ID"));
    editID = new wxTextCtrl(this, -1, wxT(""));
    labelLocation = new wxStaticText(this, -1, wxT("Location"));
    const wxString comboLocation_choices[] = {
        wxT("choice 1")
    };
    comboLocation = new InformComboBox(this, -1, "", wxDefaultPosition, wxDefaultSize, 1, comboLocation_choices, wxCB_DROPDOWN|wxCB_READONLY|wxCB_SORT);
    labelSourceFile = new wxStaticText(this, -1, wxT("Source File "));
    const wxString comboFile_choices[] = {
        wxT("choice 1")
    };
    comboFile = new InformComboBox(this, -1, "", wxDefaultPosition, wxDefaultSize, 1, comboFile_choices, wxCB_DROPDOWN|wxCB_READONLY|wxCB_SORT);
    buttonOK = new wxButton(this, wxID_OK, wxT("OK"));
    buttonCancel = new wxButton(this, wxID_CANCEL, wxT("Cancel"));

    set_properties();
    do_layout();
    // end wxGlade

  wxString line="<none>";
  comboLocation->Clear();
  comboLocation->Append(line);
  for(unsigned int i=0; i<frame->project.objects.GetCount(); i++) {
    InformData *current=&frame->project.objects[i];
    if(current->type==INF_T_ROOM) {
      comboLocation->Append(current->GetSource(INF_ID));
    }
  }
  comboLocation->SetValue(line);

  comboFile->Clear();
  for(unsigned int i=0; i<frame->project.objects.GetCount(); i++) {
    InformData *current=&frame->project.objects[i];
    if(current->type==INF_T_SOURCEFILE) {
      line=current->GetSource(INF_ID);
      comboFile->Append(line);
    }
  }
  comboFile->SetValue(line);

}


void NewObjectDialog::set_properties()
{
    // begin wxGlade: NewObjectDialog::set_properties
    SetTitle(wxT("New Object"));
    SetSize(wxSize(255, 185));
    comboLocation->SetSelection(0);
    comboFile->SetSelection(0);
    // end wxGlade
}


void NewObjectDialog::do_layout()
{
    // begin wxGlade: NewObjectDialog::do_layout
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
    wxGridSizer* grid_sizer_3 = new wxGridSizer(1, 2, 0, 0);
    wxFlexGridSizer* grid_sizer_2 = new wxFlexGridSizer(5, 2, 0, 0);
    sizer_3->Add(labelIntro, 0, 0, 0);
    grid_sizer_2->Add(labelID, 0, 0, 0);
    grid_sizer_2->Add(editID, 0, wxEXPAND, 0);
    grid_sizer_2->Add(labelLocation, 0, 0, 0);
    grid_sizer_2->Add(comboLocation, 0, wxEXPAND, 0);
    grid_sizer_2->Add(labelSourceFile, 0, 0, 0);
    grid_sizer_2->Add(comboFile, 0, wxEXPAND, 0);
    grid_sizer_2->AddGrowableCol(1);
    sizer_3->Add(grid_sizer_2, 1, wxEXPAND, 0);
    grid_sizer_3->Add(buttonOK, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0);
    grid_sizer_3->Add(buttonCancel, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0);
    sizer_3->Add(grid_sizer_3, 1, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(sizer_3);
    Layout();
    // end wxGlade
}



