// -*- C++ -*- generated by wxGlade 0.3.1 on Thu Oct 23 16:22:28 2003

#include <wx/wx.h>
#include <wx/image.h>

#ifndef MAPWIDGET_H
#define MAPWIDGET_H

// begin wxGlade: dependencies
#include "MapCanvas.h"
// end wxGlade


class MapWidget: public wxScrolledWindow {
public:
    // begin wxGlade: MapWidget::ids
    // end wxGlade

    MapWidget(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);
    void Init() { canvas->Init(); }

private:
    // begin wxGlade: MapWidget::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MapWidget::attributes
    MapCanvas* canvas;
    // end wxGlade
};


#endif // MAPWIDGET_H
