// -*- C++ -*- generated by wxGlade 0.3.1 on Thu Oct 23 16:22:28 2003

#include "MapWidget.h"

MapWidget::MapWidget(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxScrolledWindow(parent, id, pos, size, wxTAB_TRAVERSAL, "MapWidget")
{
    // begin wxGlade: MapWidget::MapWidget
    canvas = new MapCanvas(this, -1);

    set_properties();
    do_layout();
    // end wxGlade
}


void MapWidget::set_properties()
{
    // begin wxGlade: MapWidget::set_properties
    SetSize(wxSize(-1, -1));
    SetScrollRate(10, 10);
    // end wxGlade
}


void MapWidget::do_layout()
{
    // begin wxGlade: MapWidget::do_layout
    wxBoxSizer* canvasSizer = new wxBoxSizer(wxHORIZONTAL);
    canvasSizer->Add(canvas, 1, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(canvasSizer);
    // end wxGlade
}

