// -*- C++ -*- generated by wxGlade 0.3.1 on Thu Oct 09 13:32:21 2003

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/notebook.h>
// end wxGlade


#ifndef ACTOR_H
#define ACTOR_H


class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxStaticText* labelClass;
    wxComboBox* comboClass;
    wxStaticText* labelLocation;
    wxComboBox* comboLocation;
    wxStaticText* labelID;
    wxTextCtrl* editID;
    wxStaticText* labelName;
    wxTextCtrl* editName;
    wxStaticText* labelWords;
    wxTextCtrl* editWords;
    wxStaticText* labelDescription;
    wxTextCtrl* editDescription;
    wxStaticText* labelLife;
    wxTextCtrl* editLife;
    wxStaticText* labelAttributes;
    wxCheckBox* checkboxProper;
    wxCheckBox* checkboxFemale;
    wxCheckBox* checkboxConcealed;
    wxPanel* propertyPanel;
    wxComboBox* comboFilter;
    wxStaticText* labelUsed;
    wxStaticText* labelAvailable;
    wxListBox* listboxUsed;
    wxButton* buttonAdd;
    wxButton* buttonDelete;
    wxButton* buttonCode;
    wxListBox* listboxAvailable;
    wxPanel* filterPanel;
    wxNotebook* this;
    // end wxGlade
};


#endif // ACTOR_H
