// -*- C++ -*- generated by wxGlade 0.3.1 on Thu Oct 09 13:32:21 2003

#include "actor.h"


MyFrame::MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: MyFrame::MyFrame
    this = new wxNotebook(this, -1, wxDefaultPosition, wxDefaultSize, 0);
    filterPanel = new wxPanel(this, -1);
    propertyPanel = new wxPanel(this, -1);
    labelClass = new wxStaticText(propertyPanel, -1, wxT("Class"));
    const wxString comboClass_choices[] = {
        wxT("1"),
        wxT("2"),
        wxT("3"),
        wxT("4"),
        wxT("5")
    };
    comboClass = new wxComboBox(propertyPanel, -1, "", wxDefaultPosition, wxDefaultSize, 5, comboClass_choices, wxCB_DROPDOWN|wxCB_READONLY);
    labelLocation = new wxStaticText(propertyPanel, -1, wxT("Location"));
    const wxString comboLocation_choices[] = {
        wxT("1"),
        wxT("2"),
        wxT("3"),
        wxT("4"),
        wxT("5")
    };
    comboLocation = new wxComboBox(propertyPanel, -1, "", wxDefaultPosition, wxDefaultSize, 5, comboLocation_choices, wxCB_DROPDOWN|wxCB_READONLY|wxCB_SORT);
    labelID = new wxStaticText(propertyPanel, -1, wxT("ID"));
    editID = new wxTextCtrl(propertyPanel, -1, wxT(""));
    labelName = new wxStaticText(propertyPanel, -1, wxT("Name"));
    editName = new wxTextCtrl(propertyPanel, -1, wxT(""));
    labelWords = new wxStaticText(propertyPanel, -1, wxT("Words"));
    editWords = new wxTextCtrl(propertyPanel, -1, wxT(""));
    labelDescription = new wxStaticText(propertyPanel, -1, wxT("Description"));
    editDescription = new wxTextCtrl(propertyPanel, -1, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxHSCROLL);
    labelLife = new wxStaticText(propertyPanel, -1, wxT("Life"));
    editLife = new wxTextCtrl(propertyPanel, -1, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxHSCROLL);
    labelAttributes = new wxStaticText(propertyPanel, -1, wxT("Attributes"));
    checkboxProper = new wxCheckBox(propertyPanel, -1, wxT("proper"));
    checkboxFemale = new wxCheckBox(propertyPanel, -1, wxT("female"));
    checkboxConcealed = new wxCheckBox(propertyPanel, -1, wxT("concealed"));
    const wxString comboFilter_choices[] = {
        wxT("Before"),
        wxT("After"),
        wxT("React Before"),
        wxT("React After")
    };
    comboFilter = new wxComboBox(filterPanel, -1, "", wxDefaultPosition, wxDefaultSize, 4, comboFilter_choices, wxCB_DROPDOWN|wxCB_READONLY);
    labelUsed = new wxStaticText(filterPanel, -1, wxT("Used filters"));
    labelAvailable = new wxStaticText(filterPanel, -1, wxT("Available"));
    const wxString listboxUsed_choices[] = {
        wxT("Enter"),
        wxT("Take")
    };
    listboxUsed = new wxListBox(filterPanel, -1, wxDefaultPosition, wxDefaultSize, 2, listboxUsed_choices, 0);
    buttonAdd = new wxButton(filterPanel, -1, wxT("<== Add"));
    buttonDelete = new wxButton(filterPanel, -1, wxT("==> Delete"));
    buttonCode = new wxButton(filterPanel, -1, wxT("View Code"));
    const wxString listboxAvailable_choices[] = {
        wxT("Drop"),
        wxT("Leave"),
        wxT("Open")
    };
    listboxAvailable = new wxListBox(filterPanel, -1, wxDefaultPosition, wxDefaultSize, 3, listboxAvailable_choices, 0);

    set_properties();
    do_layout();
    // end wxGlade
}


void MyFrame::set_properties()
{
    // begin wxGlade: MyFrame::set_properties
    SetTitle(wxT("frame_1"));
    comboClass->SetSelection(0);
    comboLocation->SetSelection(0);
    comboFilter->SetSelection(0);
    listboxUsed->SetSelection(0);
    listboxAvailable->SetSelection(0);
    // end wxGlade
}


void MyFrame::do_layout()
{
    // begin wxGlade: MyFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxFlexGridSizer* grid_sizer_3 = new wxFlexGridSizer(3, 1, 0, 0);
    wxFlexGridSizer* grid_sizer_4 = new wxFlexGridSizer(1, 3, 0, 0);
    wxFlexGridSizer* grid_sizer_7 = new wxFlexGridSizer(2, 3, 0, 0);
    wxFlexGridSizer* grid_sizer_8 = new wxFlexGridSizer(3, 1, 0, 0);
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(7, 2, 0, 0);
    wxGridSizer* grid_sizer_2 = new wxGridSizer(1, 3, 0, 0);
    grid_sizer_1->Add(labelClass, 0, 0, 0);
    grid_sizer_1->Add(comboClass, 0, wxEXPAND, 0);
    grid_sizer_1->Add(labelLocation, 0, 0, 0);
    grid_sizer_1->Add(comboLocation, 0, wxEXPAND, 0);
    grid_sizer_1->Add(labelID, 0, 0, 0);
    grid_sizer_1->Add(editID, 0, wxEXPAND, 0);
    grid_sizer_1->Add(labelName, 0, 0, 0);
    grid_sizer_1->Add(editName, 0, wxEXPAND, 0);
    grid_sizer_1->Add(labelWords, 0, 0, 0);
    grid_sizer_1->Add(editWords, 0, wxEXPAND, 0);
    grid_sizer_1->Add(labelDescription, 0, 0, 0);
    grid_sizer_1->Add(editDescription, 0, wxEXPAND, 0);
    grid_sizer_1->Add(labelLife, 0, 0, 0);
    grid_sizer_1->Add(editLife, 0, wxEXPAND, 0);
    grid_sizer_1->Add(labelAttributes, 0, 0, 0);
    grid_sizer_2->Add(checkboxProper, 0, 0, 0);
    grid_sizer_2->Add(checkboxFemale, 0, 0, 0);
    grid_sizer_2->Add(checkboxConcealed, 0, 0, 0);
    grid_sizer_1->Add(grid_sizer_2, 1, wxEXPAND, 0);
    propertyPanel->SetAutoLayout(true);
    propertyPanel->SetSizer(grid_sizer_1);
    grid_sizer_1->Fit(propertyPanel);
    grid_sizer_1->SetSizeHints(propertyPanel);
    grid_sizer_1->AddGrowableRow(5);
    grid_sizer_1->AddGrowableRow(6);
    grid_sizer_1->AddGrowableCol(1);
    grid_sizer_3->Add(comboFilter, 0, wxEXPAND, 0);
    grid_sizer_7->Add(labelUsed, 0, 0, 0);
    grid_sizer_7->Add(20, 20, 0, 0, 0);
    grid_sizer_7->Add(labelAvailable, 0, 0, 0);
    grid_sizer_7->Add(listboxUsed, 0, wxEXPAND, 0);
    grid_sizer_8->Add(buttonAdd, 0, wxALIGN_CENTER_VERTICAL, 0);
    grid_sizer_8->Add(buttonDelete, 0, wxALIGN_CENTER_VERTICAL, 0);
    grid_sizer_8->Add(buttonCode, 0, wxALIGN_CENTER_VERTICAL, 0);
    grid_sizer_8->AddGrowableRow(0);
    grid_sizer_8->AddGrowableRow(1);
    grid_sizer_8->AddGrowableRow(2);
    grid_sizer_7->Add(grid_sizer_8, 1, wxEXPAND, 0);
    grid_sizer_7->Add(listboxAvailable, 0, wxEXPAND, 0);
    grid_sizer_7->AddGrowableRow(1);
    grid_sizer_7->AddGrowableCol(0);
    grid_sizer_7->AddGrowableCol(2);
    grid_sizer_3->Add(grid_sizer_7, 1, wxEXPAND, 0);
    grid_sizer_4->AddGrowableCol(0);
    grid_sizer_4->AddGrowableCol(1);
    grid_sizer_3->Add(grid_sizer_4, 1, wxEXPAND, 0);
    filterPanel->SetAutoLayout(true);
    filterPanel->SetSizer(grid_sizer_3);
    grid_sizer_3->Fit(filterPanel);
    grid_sizer_3->SetSizeHints(filterPanel);
    grid_sizer_3->AddGrowableRow(1);
    grid_sizer_3->AddGrowableCol(0);
    this->AddPage(propertyPanel, wxT("Property"));
    this->AddPage(filterPanel, wxT("Filter"));
    sizer_1->Add(new wxNotebookSizer(this), 1, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    sizer_1->SetSizeHints(this);
    Layout();
    // end wxGlade
}



