// -*- C++ -*- generated by wxGlade 0.3.1 on Mon Oct 20 10:21:28 2003

#include "adddoor.h"


AddDoor::AddDoor(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxTHICK_FRAME)
{
    // begin wxGlade: AddDoor::AddDoor
    labelFrom = new wxStaticText(this, -1, wxT("From"));
    text_ctrl_1 = new wxTextCtrl(this, -1, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    labelTo = new wxStaticText(this, -1, wxT("To"));
    text_ctrl_2 = new wxTextCtrl(this, -1, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    labelStatus = new wxStaticText(this, -1, wxT("Status  "));
    checkbox_1 = new wxCheckBox(this, -1, wxT("Openable"));
    checkbox_2 = new wxCheckBox(this, -1, wxT("Open"));
    labelState = new wxStaticText(this, -1, wxT("State"));
    checkbox_3 = new wxCheckBox(this, -1, wxT("Lockable"));
    checkbox_4 = new wxCheckBox(this, -1, wxT("Locked"));
    labelKey = new wxStaticText(this, -1, wxT("Key"));
    const wxString comboKey_choices[] = {
        wxT("choice 1")
    };
    comboKey = new InformCombo(this, -1, "", wxDefaultPosition, wxDefaultSize, 1, comboKey_choices, wxCB_DROPDOWN|wxCB_READONLY|wxCB_SORT);
    buttonCreateKey = new wxButton(this, DLG_ADDROOM_CREATEKEY, wxT("Create Key..."));
    buttonOK = new wxButton(this, wxID_OK, wxT("OK"));
    buttonCancel = new wxButton(this, wxID_CANCEL, wxT("Cancel"));

    set_properties();
    do_layout();
    // end wxGlade
}


void AddDoor::set_properties()
{
    // begin wxGlade: AddDoor::set_properties
    SetTitle(wxT("Add Door"));
    SetSize(wxSize(300, 200));
    comboKey->SetSelection(0);
    // end wxGlade
}


void AddDoor::do_layout()
{
    // begin wxGlade: AddDoor::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxHORIZONTAL);
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(2, 1, 0, 0);
    wxFlexGridSizer* grid_sizer_3 = new wxFlexGridSizer(1, 2, 0, 0);
    wxFlexGridSizer* grid_sizer_2 = new wxFlexGridSizer(5, 2, 0, 0);
    wxFlexGridSizer* grid_sizer_6 = new wxFlexGridSizer(1, 2, 0, 0);
    wxGridSizer* grid_sizer_5 = new wxGridSizer(1, 2, 0, 0);
    wxGridSizer* grid_sizer_4 = new wxGridSizer(1, 2, 0, 0);
    grid_sizer_2->Add(labelFrom, 0, 0, 0);
    grid_sizer_2->Add(text_ctrl_1, 0, wxEXPAND, 0);
    grid_sizer_2->Add(labelTo, 0, 0, 0);
    grid_sizer_2->Add(text_ctrl_2, 0, wxEXPAND, 0);
    grid_sizer_2->Add(labelStatus, 0, 0, 0);
    grid_sizer_4->Add(checkbox_1, 0, 0, 0);
    grid_sizer_4->Add(checkbox_2, 0, 0, 0);
    grid_sizer_2->Add(grid_sizer_4, 1, wxEXPAND, 0);
    grid_sizer_2->Add(labelState, 0, 0, 0);
    grid_sizer_5->Add(checkbox_3, 0, 0, 0);
    grid_sizer_5->Add(checkbox_4, 0, 0, 0);
    grid_sizer_2->Add(grid_sizer_5, 1, wxEXPAND, 0);
    grid_sizer_2->Add(labelKey, 0, 0, 0);
    grid_sizer_6->Add(comboKey, 0, wxEXPAND, 0);
    grid_sizer_6->Add(buttonCreateKey, 0, 0, 0);
    grid_sizer_6->AddGrowableCol(0);
    grid_sizer_2->Add(grid_sizer_6, 1, wxEXPAND, 0);
    grid_sizer_2->AddGrowableRow(0);
    grid_sizer_2->AddGrowableRow(1);
    grid_sizer_2->AddGrowableRow(2);
    grid_sizer_2->AddGrowableRow(3);
    grid_sizer_2->AddGrowableRow(4);
    grid_sizer_2->AddGrowableCol(1);
    grid_sizer_1->Add(grid_sizer_2, 1, wxEXPAND, 0);
    grid_sizer_3->Add(buttonOK, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    grid_sizer_3->Add(buttonCancel, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    grid_sizer_3->AddGrowableCol(0);
    grid_sizer_3->AddGrowableCol(1);
    grid_sizer_1->Add(grid_sizer_3, 1, wxEXPAND, 0);
    grid_sizer_1->AddGrowableRow(0);
    grid_sizer_1->AddGrowableRow(1);
    grid_sizer_1->AddGrowableCol(0);
    sizer_1->Add(grid_sizer_1, 1, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}



