// -*- C++ -*- generated by wxGlade 0.3.1 on Mon Oct 06 17:01:42 2003

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/event.h>

#ifndef DLGPREFERENCES_H
#define DLGPREFERENCES_H

// begin wxGlade: dependencies
#include <wx/spinctrl.h>
#include <wx/notebook.h>
// end wxGlade

enum {
  BUTTON_BROWSE_TERP=1,
  BUTTON_BROWSE_COMPILER,
  BUTTON_BROWSE_LIBRARY,
  BUTTON_BROWSE_TEMPLATE
};

class DlgPreferences: public wxDialog {
public:
    // begin wxGlade: DlgPreferences::ids
    // end wxGlade

    DlgPreferences(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

    void Set(const wxString& compilerPath, const wxString& libraryPath,
             const wxString& terpPath, const wxString& templatePath, 
             const wxString& author, bool reload, bool warnOnExit, 
             int indentSize, bool useTabs);

    void Get(wxString *compilerPath, wxString *libraryPath, wxString *terpPath,
             wxString *templatePath, wxString *author, bool *reload,
             bool *warnOnExit, int *indentSize, bool *useTabs);

private:
    void OnBrowseTerp(wxCommandEvent &event);
    void OnBrowseLibrary(wxCommandEvent &event);
    void OnBrowseCompiler(wxCommandEvent &event);
    void OnBrowseTemplate(wxCommandEvent &event);

    // begin wxGlade: DlgPreferences::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DlgPreferences::attributes
    wxStaticText* label_5;
    wxTextCtrl* editCompilerPath;
    wxButton* buttonBrowseCompiler;
    wxStaticText* label_2;
    wxTextCtrl* editLibraryPath;
    wxButton* buttonBrowseLibrary;
    wxStaticText* label_6;
    wxTextCtrl* editTerpPath;
    wxButton* buttonBrowseTerp;
    wxStaticText* labelTemplate;
    wxTextCtrl* editTemplatePath;
    wxButton* buttonBrowseTemplate;
    wxStaticText* label_7;
    wxTextCtrl* editAuthor;
    wxStaticText* label_8;
    wxCheckBox* checkboxReloadActive;
    wxStaticText* labelShutdown;
    wxCheckBox* checkboxWarnUnsaved;
    wxStaticText* label_1;
    wxSpinCtrl* spinIndentSize;
    wxRadioButton* radioSpace;
    wxRadioButton* radioTab;
    wxPanel* generalPanel;
    wxStaticText* label_9;
    wxSpinCtrl* spinWidth;
    wxStaticText* label_10;
    wxSpinCtrl* spinHeight;
    wxPanel* mapPanel;
    wxNotebook* notebook_2;
    wxButton* buttonOK;
    wxButton* buttonCancel;
    // end wxGlade

  // any class wishing to process wxWindows events must use this macro
  DECLARE_EVENT_TABLE()
};


#endif // DLGPREFERENCES_H
