// -*- C++ -*- generated by wxGlade 0.3.1 on Thu Oct 09 13:24:26 2003

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/notebook.h>
// end wxGlade


#ifndef OBJECTS_H
#define OBJECTS_H


class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxStaticText* labelClass;
    wxComboBox* comboClass;
    wxStaticText* labelLocation;
    wxComboBox* comboLocation;
    wxStaticText* labelID;
    wxTextCtrl* editID;
    wxStaticText* labelName;
    wxTextCtrl* editName;
    wxStaticText* labelNouns;
    wxTextCtrl* editWords;
    wxStaticText* labelDescription;
    wxTextCtrl* editDescription;
    wxStaticText* labelAttributes;
    wxCheckBox* checkboxGeneral;
    wxCheckBox* checkboxScenery;
    wxCheckBox* checkboxConcealed;
    wxCheckBox* checkboxAnimate;
    wxCheckBox* checkboxLight;
    wxCheckBox* checkboxClothing;
    wxCheckBox* checkboxWorn;
    wxCheckBox* checkboxFemale;
    wxCheckBox* checkboxTransparent;
    wxPanel* propertyPanel;
    wxNotebook* notebook_1;
    // end wxGlade
};


#endif // OBJECTS_H
