// -*- C++ -*- generated by wxGlade 0.3.1 on Thu Oct 09 13:24:26 2003

#include "objects.h"


MyFrame::MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: MyFrame::MyFrame
    notebook_1 = new wxNotebook(this, -1, wxDefaultPosition, wxDefaultSize, 0);
    propertyPanel = new wxPanel(notebook_1, -1);
    labelClass = new wxStaticText(propertyPanel, -1, wxT("Class"));
    const wxString comboClass_choices[] = {
        wxT("1"),
        wxT("2"),
        wxT("3"),
        wxT("4"),
        wxT("5")
    };
    comboClass = new wxComboBox(propertyPanel, -1, "", wxDefaultPosition, wxDefaultSize, 5, comboClass_choices, wxCB_DROPDOWN|wxCB_READONLY);
    labelLocation = new wxStaticText(propertyPanel, -1, wxT("Location"));
    const wxString comboLocation_choices[] = {
        wxT("1"),
        wxT("2"),
        wxT("3"),
        wxT("4"),
        wxT("5")
    };
    comboLocation = new wxComboBox(propertyPanel, -1, "", wxDefaultPosition, wxDefaultSize, 5, comboLocation_choices, wxCB_DROPDOWN|wxCB_READONLY|wxCB_SORT);
    labelID = new wxStaticText(propertyPanel, -1, wxT("ID"));
    editID = new wxTextCtrl(propertyPanel, -1, wxT(""));
    labelName = new wxStaticText(propertyPanel, -1, wxT("Name"));
    editName = new wxTextCtrl(propertyPanel, -1, wxT(""));
    labelNouns = new wxStaticText(propertyPanel, -1, wxT("Words"));
    editWords = new wxTextCtrl(propertyPanel, -1, wxT(""));
    labelDescription = new wxStaticText(propertyPanel, -1, wxT("Description"));
    editDescription = new wxTextCtrl(propertyPanel, -1, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    labelAttributes = new wxStaticText(propertyPanel, -1, wxT("Attributes"));
    checkboxGeneral = new wxCheckBox(propertyPanel, -1, wxT("general"));
    checkboxScenery = new wxCheckBox(propertyPanel, -1, wxT("scenery"));
    checkboxConcealed = new wxCheckBox(propertyPanel, -1, wxT("concealed"));
    checkboxAnimate = new wxCheckBox(propertyPanel, -1, wxT("animate"));
    checkboxLight = new wxCheckBox(propertyPanel, -1, wxT("light"));
    checkboxClothing = new wxCheckBox(propertyPanel, -1, wxT("clothing"));
    checkboxWorn = new wxCheckBox(propertyPanel, -1, wxT("worn"));
    checkboxFemale = new wxCheckBox(propertyPanel, -1, wxT("female"));
    checkboxTransparent = new wxCheckBox(propertyPanel, -1, wxT("transparent"));

    set_properties();
    do_layout();
    // end wxGlade
}


void MyFrame::set_properties()
{
    // begin wxGlade: MyFrame::set_properties
    SetTitle(wxT("frame_1"));
    comboClass->SetSelection(0);
    comboLocation->SetSelection(0);
    // end wxGlade
}


void MyFrame::do_layout()
{
    // begin wxGlade: MyFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(6, 2, 0, 0);
    wxGridSizer* grid_sizer_2 = new wxGridSizer(3, 3, 0, 0);
    grid_sizer_1->Add(labelClass, 0, 0, 0);
    grid_sizer_1->Add(comboClass, 0, wxEXPAND, 0);
    grid_sizer_1->Add(labelLocation, 0, 0, 0);
    grid_sizer_1->Add(comboLocation, 0, wxEXPAND, 0);
    grid_sizer_1->Add(labelID, 0, 0, 0);
    grid_sizer_1->Add(editID, 0, wxEXPAND, 0);
    grid_sizer_1->Add(labelName, 0, 0, 0);
    grid_sizer_1->Add(editName, 0, wxEXPAND, 0);
    grid_sizer_1->Add(labelNouns, 0, 0, 0);
    grid_sizer_1->Add(editWords, 0, wxEXPAND, 0);
    grid_sizer_1->Add(labelDescription, 0, 0, 0);
    grid_sizer_1->Add(editDescription, 0, wxEXPAND, 0);
    grid_sizer_1->Add(labelAttributes, 0, 0, 0);
    grid_sizer_2->Add(checkboxGeneral, 0, 0, 0);
    grid_sizer_2->Add(checkboxScenery, 0, 0, 0);
    grid_sizer_2->Add(checkboxConcealed, 0, 0, 0);
    grid_sizer_2->Add(checkboxAnimate, 0, 0, 0);
    grid_sizer_2->Add(checkboxLight, 0, 0, 0);
    grid_sizer_2->Add(checkboxClothing, 0, 0, 0);
    grid_sizer_2->Add(checkboxWorn, 0, 0, 0);
    grid_sizer_2->Add(checkboxFemale, 0, 0, 0);
    grid_sizer_2->Add(checkboxTransparent, 0, 0, 0);
    grid_sizer_1->Add(grid_sizer_2, 1, wxEXPAND, 0);
    propertyPanel->SetAutoLayout(true);
    propertyPanel->SetSizer(grid_sizer_1);
    grid_sizer_1->Fit(propertyPanel);
    grid_sizer_1->SetSizeHints(propertyPanel);
    grid_sizer_1->AddGrowableRow(5);
    grid_sizer_1->AddGrowableCol(1);
    notebook_1->AddPage(propertyPanel, wxT("tab1"));
    sizer_1->Add(new wxNotebookSizer(notebook_1), 1, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    sizer_1->SetSizeHints(this);
    Layout();
    // end wxGlade
}

