// -*- C++ -*- generated by wxGlade 0.3.1 on Fri Oct 10 10:29:01 2003

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/notebook.h>
// end wxGlade


#ifndef ROOM_H
#define ROOM_H


class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxStaticText* labelClass;
    wxComboBox* comboClass;
    wxStaticText* labelID;
    wxTextCtrl* editID;
    wxStaticText* labelName;
    wxTextCtrl* editName;
    wxStaticText* labelScenery;
    wxTextCtrl* editScenery;
    wxTextCtrl* editDescription;
    wxStaticText* labelAttributes;
    wxCheckBox* checkboxLight;
    wxComboBox* comboNW;
    wxComboBox* comboN;
    wxComboBox* comboNE;
    wxComboBox* comboW;
    wxStaticText* labelExits;
    wxComboBox* comboE;
    wxComboBox* comboSW;
    wxComboBox* comboS;
    wxComboBox* comboSE;
    wxStaticText* labelUp;
    wxComboBox* comboUp;
    wxStaticText* labelDown;
    wxComboBox* comboDown;
    wxStaticText* labelIn;
    wxComboBox* comboIn;
    wxStaticText* labelOut;
    wxComboBox* comboOut;
    wxPanel* propertyPanel;
    wxNotebook* notebook_1;
    // end wxGlade
};


#endif // ROOM_H
